server:
  servlet:
    context-path: /ms-data-master-campaign/api/v1
  port: 8084

spring:
  application:
    name: ms-data-master-campaign
  datasource:
    url: jdbc:postgresql://sequrra-postgres-prod.czgs6oy66x99.ap-southeast-3.rds.amazonaws.com:5432/sequrra
    username: sequrra_root
    password: g9fpiEpET9AAXC8kQygE
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 300000
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://sequrra-postgres-prod.czgs6oy66x99.ap-southeast-3.rds.amazonaws.com:5432/sequrra
    user: sequrra_root
    password: g9fpiEpET9AAXC8kQygE
    schemas: ms-data-master-campaign-svc
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: true
    baseline-version: 1.1
    locations: classpath:db/migration
    out-of-order: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none


common:
  pageable:
    size: 100
    page: 0
  sorting: ASC

#endpoint-configuration
endpoint:
  campaign:
    base: /campaign
    get-all: /
    get-by-id: /{id}
    get-by-campaign-status: campaignStatus/{campaignStatus}
    update: /{id}
    delete: /{id}
  campaign-scan-log:
    base: /campaign-scan-log
    get-all: /
    get-by-id: /{id}
    update: /{id}
    delete: /{id}
    get-count-scan-by-email: /countScanByEmail/{email}
  coupon:
    base: /coupon
    get-all: /
    get-by-id: /{id}
    delete: /{id}
    get-by-coupon-status: /campaignStatus/{campaignStatus}


aws:
  region: ap-southeast-3
  credentials:
    accessKey: AKIAYM7PN53LNWVX4GM3
    secretKey: 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
  s3:
    bucket: sequrra-media-dev
#kafka:
#  producer:
#    bootstrap-servers: 139.162.36.148:9093
#    key-serializer: org.apache.kafka.common.serialization.StringSerializer
#    value-serializer: org.apache.kafka.common.serialization.StringSerializer
#  topics:
#      - name: account.auth.events
#        num-partitions: 3
#        replication-factor: 1